name: "Conventional Commits PR Check"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<p><a href="https://maps.app.goo.gl/53J9jGw7a8MTquxe6?g_st=ac">https://maps.app.goo.gl/53J9jGw7a8MTquxe6?g_st=ac</a></p>
